/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_Abort_RequestPDU_H_
#define	_Abort_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Abort_RequestPDU__reason {
	Abort_RequestPDU__reason_other	= 0,
	Abort_RequestPDU__reason_unrecognized_service	= 1,
	Abort_RequestPDU__reason_invalid_reqID	= 2,
	Abort_RequestPDU__reason_invalid_argument	= 3,
	Abort_RequestPDU__reason_invalid_result	= 4,
	Abort_RequestPDU__reason_max_serv_outstanding_exceeded	= 5
} e_Abort_RequestPDU__reason;

/* Abort-RequestPDU */
typedef struct Abort_RequestPDU {
	OCTET_STRING_t	 associationId;
	long	 reason;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Abort_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Abort_RequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _Abort_RequestPDU_H_ */
#include <asn_internal.h>
