/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_ACSIClass_H_
#define	_ACSIClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ACSIClass {
	ACSIClass_reserved	= 0,
	ACSIClass_data_object	= 1,
	ACSIClass_data_set	= 2,
	ACSIClass_brcb	= 3,
	ACSIClass_urcb	= 4,
	ACSIClass_lcb	= 5,
	ACSIClass_log	= 6,
	ACSIClass_sgcb	= 7,
	ACSIClass_gocb	= 8,
	ACSIClass_msvcb	= 10
} e_ACSIClass;

/* ACSIClass */
typedef long	 ACSIClass_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ACSIClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ACSIClass;
asn_struct_free_f ACSIClass_free;
asn_struct_print_f ACSIClass_print;
asn_constr_check_f ACSIClass_constraint;
per_type_decoder_f ACSIClass_decode_uper;
per_type_encoder_f ACSIClass_encode_uper;
per_type_decoder_f ACSIClass_decode_aper;
per_type_encoder_f ACSIClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ACSIClass_H_ */
#include <asn_internal.h>
