/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_INT8 (-128)
#define max_val_INT8 (127)
#define min_val_INT16 (-32768)
#define max_val_INT16 (32767)
#define min_val_INT32 (-2147483648)
#define max_val_INT32 (2147483647)
#define min_val_INT8U (0)
#define max_val_INT8U (255)
#define min_val_INT16U (0)
#define max_val_INT16U (65535)
#define min_val_INT24U (0)
#define max_val_INT24U (16777215)
#define min_val_INT32U (0)
#define max_val_INT32U (321)
#define min_val_INT64U (0)
#define max_val_INT64U (321)
#define min_val_ServiceError (0)
#define max_val_ServiceError (14)
#define min_val_AddCause (0)
#define max_val_AddCause (27)
#define min_val_SmpMod (0)
#define max_val_SmpMod (2)
#define min_val_ACSIClass (0)
#define max_val_ACSIClass (10)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
