/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_AssociateNegotiate_RequestPDU_H_
#define	_AssociateNegotiate_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "INT16U.h"
#include "INT32U.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AssociateNegotiate-RequestPDU */
typedef struct AssociateNegotiate_RequestPDU {
	INT16U_t	 apduSize;
	INT32U_t	 asduSize;
	INT32U_t	 protocolVersion;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AssociateNegotiate_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AssociateNegotiate_RequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _AssociateNegotiate_RequestPDU_H_ */
#include <asn_internal.h>
