/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_Associate_ResponsePDU_H_
#define	_Associate_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "ServiceError.h"
#include "UtcTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Associate-ResponsePDU */
typedef struct Associate_ResponsePDU {
	OCTET_STRING_t	 associationId;
	ServiceError_t	 serviceError;
	struct Associate_ResponsePDU__authenticationParameter {
		OCTET_STRING_t	 signatureCertificate;
		UtcTime_t	 signedTime;
		OCTET_STRING_t	 signedValue;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *authenticationParameter;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Associate_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Associate_ResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _Associate_ResponsePDU_H_ */
#include <asn_internal.h>
