/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_Associate_RequestPDU_H_
#define	_Associate_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VisibleString129.h"
#include <OCTET_STRING.h>
#include "UtcTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Associate-RequestPDU */
typedef struct Associate_RequestPDU {
	VisibleString129_t	*serverAccessPointReference;	/* OPTIONAL */
	struct Associate_RequestPDU__authenticationParameter {
		OCTET_STRING_t	 signatureCertificate;
		UtcTime_t	 signedTime;
		OCTET_STRING_t	 signedValue;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *authenticationParameter;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Associate_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Associate_RequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _Associate_RequestPDU_H_ */
#include <asn_internal.h>
