/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_BRCB_H_
#define	_BRCB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VisibleString129.h"
#include <BOOLEAN.h>
#include "ObjectReference.h"
#include "INT32U.h"
#include "RCBOptFlds.h"
#include "INT16U.h"
#include "TriggerConditions.h"
#include "EntryID.h"
#include "EntryTime.h"
#include "INT16.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BRCB */
typedef struct BRCB {
	VisibleString129_t	 rptID;
	BOOLEAN_t	 rptEna;
	ObjectReference_t	 datSet;
	INT32U_t	 confRev;
	RCBOptFlds_t	 optFlds;
	INT32U_t	 bufTm;
	INT16U_t	 sqNum;
	TriggerConditions_t	 trgOps;
	INT32U_t	 intgPd;
	BOOLEAN_t	 gi;
	BOOLEAN_t	 purgeBuf;
	EntryID_t	 entryID;
	EntryTime_t	 timeOfEntry;
	INT16_t	*resvTms;	/* OPTIONAL */
	OCTET_STRING_t	*owner;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BRCB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BRCB;
extern asn_SEQUENCE_specifics_t asn_SPC_BRCB_specs_1;
extern asn_TYPE_member_t asn_MBR_BRCB_1[15];

#ifdef __cplusplus
}
#endif

#endif	/* _BRCB_H_ */
#include <asn_internal.h>
