/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_Check_H_
#define	_Check_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Check {
	Check_synchrocheck	= 0,
	Check_interlock_check	= 1
} e_Check;

/* Check */
typedef BIT_STRING_t	 Check_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Check_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Check;
asn_struct_free_f Check_free;
asn_struct_print_f Check_print;
asn_constr_check_f Check_constraint;
per_type_decoder_f Check_decode_uper;
per_type_encoder_f Check_encode_uper;
per_type_decoder_f Check_decode_aper;
per_type_encoder_f Check_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Check_H_ */
#include <asn_internal.h>
