/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_DataDefinition_H_
#define	_DataDefinition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceError.h"
#include <NULL.h>
#include "INT8U.h"
#include "INT32.h"
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include "ObjectName.h"
#include "FunctionalConstraint.h"
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DataDefinition_PR {
	DataDefinition_PR_NOTHING,	/* No components present */
	DataDefinition_PR_error,
	DataDefinition_PR_array,
	DataDefinition_PR_structure,
	DataDefinition_PR_boolean,
	DataDefinition_PR_int8,
	DataDefinition_PR_int16,
	DataDefinition_PR_int32,
	DataDefinition_PR_int64,
	DataDefinition_PR_int8u,
	DataDefinition_PR_int16u,
	DataDefinition_PR_int32u,
	DataDefinition_PR_int64u,
	DataDefinition_PR_float32,
	DataDefinition_PR_float64,
	DataDefinition_PR_bit_string,
	DataDefinition_PR_octet_string,
	DataDefinition_PR_visible_string,
	DataDefinition_PR_unicode_string,
	DataDefinition_PR_utc_time,
	DataDefinition_PR_binary_time,
	DataDefinition_PR_quality,
	DataDefinition_PR_dbpos,
	DataDefinition_PR_tcmd,
	DataDefinition_PR_check
} DataDefinition_PR;

/* Forward declarations */
struct DataDefinition;

/* Forward definitions */
typedef struct DataDefinition__structure__Member {
	ObjectName_t	 name;
	FunctionalConstraint_t	*fc;	/* OPTIONAL */
	struct DataDefinition	*type;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataDefinition__structure__Member;

/* DataDefinition */
typedef struct DataDefinition {
	DataDefinition_PR present;
	union DataDefinition_u {
		ServiceError_t	 error;
		struct DataDefinition__array {
			INT32_t	 numberOfElement;
			struct DataDefinition	*elementType;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} array;
		struct DataDefinition__structure {
			A_SEQUENCE_OF(DataDefinition__structure__Member) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} structure;
		NULL_t	 boolean;
		NULL_t	 int8;
		NULL_t	 int16;
		NULL_t	 int32;
		NULL_t	 int64;
		NULL_t	 int8u;
		NULL_t	 int16u;
		NULL_t	 int32u;
		NULL_t	 int64u;
		NULL_t	 float32;
		NULL_t	 float64;
		INT8U_t	 bit_string;
		INT8U_t	 octet_string;
		INT8U_t	 visible_string;
		INT8U_t	 unicode_string;
		NULL_t	 utc_time;
		NULL_t	 binary_time;
		NULL_t	 quality;
		NULL_t	 dbpos;
		NULL_t	 tcmd;
		NULL_t	 check;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataDefinition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataDefinition;
extern asn_CHOICE_specifics_t asn_SPC_DataDefinition_specs_1;
extern asn_TYPE_member_t asn_MBR_DataDefinition_1[24];
extern asn_per_constraints_t asn_PER_type_DataDefinition_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DataDefinition.h"

#endif	/* _DataDefinition_H_ */
#include <asn_internal.h>
