/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_ErrorPDU_H_
#define	_ErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceError.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ErrorPDU */
typedef ServiceError_t	 ErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ErrorPDU;
asn_struct_free_f ErrorPDU_free;
asn_struct_print_f ErrorPDU_print;
asn_constr_check_f ErrorPDU_constraint;
per_type_decoder_f ErrorPDU_decode_uper;
per_type_encoder_f ErrorPDU_encode_uper;
per_type_decoder_f ErrorPDU_decode_aper;
per_type_encoder_f ErrorPDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ErrorPDU_H_ */
#include <asn_internal.h>
