/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_FileEntry_H_
#define	_FileEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VisibleString129.h"
#include "INT32U.h"
#include "UtcTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileEntry */
typedef struct FileEntry {
	VisibleString129_t	 fileName;
	INT32U_t	 fileSize;
	UtcTime_t	 lastModified;
	INT32U_t	 checkSum;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileEntry;

#ifdef __cplusplus
}
#endif

#endif	/* _FileEntry_H_ */
#include <asn_internal.h>
