/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_FLOAT32_H_
#define	_FLOAT32_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FLOAT32 */
typedef OCTET_STRING_t	 FLOAT32_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FLOAT32_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FLOAT32;
asn_struct_free_f FLOAT32_free;
asn_struct_print_f FLOAT32_print;
asn_constr_check_f FLOAT32_constraint;
per_type_decoder_f FLOAT32_decode_uper;
per_type_encoder_f FLOAT32_encode_uper;
per_type_decoder_f FLOAT32_decode_aper;
per_type_encoder_f FLOAT32_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FLOAT32_H_ */
#include <asn_internal.h>
