/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_FunctionalConstraint_H_
#define	_FunctionalConstraint_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FunctionalConstraint */
typedef VisibleString_t	 FunctionalConstraint_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FunctionalConstraint_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FunctionalConstraint;
asn_struct_free_f FunctionalConstraint_free;
asn_struct_print_f FunctionalConstraint_print;
asn_constr_check_f FunctionalConstraint_constraint;
per_type_decoder_f FunctionalConstraint_decode_uper;
per_type_encoder_f FunctionalConstraint_encode_uper;
per_type_decoder_f FunctionalConstraint_decode_aper;
per_type_encoder_f FunctionalConstraint_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FunctionalConstraint_H_ */
#include <asn_internal.h>
