/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_GetAllDataValues_ResponsePDU_H_
#define	_GetAllDataValues_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "SubReference.h"
#include "Data.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct GetAllDataValues_ResponsePDU__data__Member {
	SubReference_t	 reference;
	Data_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAllDataValues_ResponsePDU__data__Member;

/* GetAllDataValues-ResponsePDU */
typedef struct GetAllDataValues_ResponsePDU {
	struct GetAllDataValues_ResponsePDU__data {
		A_SEQUENCE_OF(GetAllDataValues_ResponsePDU__data__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} data;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAllDataValues_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetAllDataValues_ResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetAllDataValues_ResponsePDU_H_ */
#include <asn_internal.h>
