/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_GetAllCBValues_ResponsePDU_H_
#define	_GetAllCBValues_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "SubReference.h"
#include "BRCB.h"
#include "URCB.h"
#include "LCB.h"
#include "SGCB.h"
#include "GoCB.h"
#include "MSVCB.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetAllCBValues_ResponsePDU__cbValue__Member__value_PR {
	GetAllCBValues_ResponsePDU__cbValue__Member__value_PR_NOTHING,	/* No components present */
	GetAllCBValues_ResponsePDU__cbValue__Member__value_PR_brcb,
	GetAllCBValues_ResponsePDU__cbValue__Member__value_PR_urcb,
	GetAllCBValues_ResponsePDU__cbValue__Member__value_PR_lcb,
	GetAllCBValues_ResponsePDU__cbValue__Member__value_PR_sgcb,
	GetAllCBValues_ResponsePDU__cbValue__Member__value_PR_gocb,
	GetAllCBValues_ResponsePDU__cbValue__Member__value_PR_msvcb
} GetAllCBValues_ResponsePDU__cbValue__Member__value_PR;

/* Forward definitions */
typedef struct GetAllCBValues_ResponsePDU__cbValue__Member {
	SubReference_t	 reference;
	struct GetAllCBValues_ResponsePDU__cbValue__Member__value {
		GetAllCBValues_ResponsePDU__cbValue__Member__value_PR present;
		union GetAllCBValues_ResponsePDU__cbValue__Member__value_u {
			BRCB_t	 brcb;
			URCB_t	 urcb;
			LCB_t	 lcb;
			SGCB_t	 sgcb;
			GoCB_t	 gocb;
			MSVCB_t	 msvcb;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAllCBValues_ResponsePDU__cbValue__Member;

/* GetAllCBValues-ResponsePDU */
typedef struct GetAllCBValues_ResponsePDU {
	struct GetAllCBValues_ResponsePDU__cbValue {
		A_SEQUENCE_OF(GetAllCBValues_ResponsePDU__cbValue__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} cbValue;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAllCBValues_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetAllCBValues_ResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetAllCBValues_ResponsePDU_H_ */
#include <asn_internal.h>
