/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_GetBRCBValues_ResponsePDU_H_
#define	_GetBRCBValues_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "ServiceError.h"
#include "BRCB.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetBRCBValues_ResponsePDU__brcb__Member_PR {
	GetBRCBValues_ResponsePDU__brcb__Member_PR_NOTHING,	/* No components present */
	GetBRCBValues_ResponsePDU__brcb__Member_PR_error,
	GetBRCBValues_ResponsePDU__brcb__Member_PR_value
} GetBRCBValues_ResponsePDU__brcb__Member_PR;

/* Forward definitions */
typedef struct GetBRCBValues_ResponsePDU__brcb__Member {
	GetBRCBValues_ResponsePDU__brcb__Member_PR present;
	union GetBRCBValues_ResponsePDU__brcb__Member_u {
		ServiceError_t	 error;
		BRCB_t	 value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetBRCBValues_ResponsePDU__brcb__Member;

/* GetBRCBValues-ResponsePDU */
typedef struct GetBRCBValues_ResponsePDU {
	struct GetBRCBValues_ResponsePDU__brcb {
		A_SEQUENCE_OF(GetBRCBValues_ResponsePDU__brcb__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} brcb;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetBRCBValues_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetBRCBValues_ResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetBRCBValues_ResponsePDU_H_ */
#include <asn_internal.h>
