/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_GetDataSetDirectory_ResponsePDU_H_
#define	_GetDataSetDirectory_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "ObjectReference.h"
#include "FunctionalConstraint.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct GetDataSetDirectory_ResponsePDU__memberData__Member {
	ObjectReference_t	 reference;
	FunctionalConstraint_t	 fc;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetDataSetDirectory_ResponsePDU__memberData__Member;

/* GetDataSetDirectory-ResponsePDU */
typedef struct GetDataSetDirectory_ResponsePDU {
	struct GetDataSetDirectory_ResponsePDU__memberData {
		A_SEQUENCE_OF(GetDataSetDirectory_ResponsePDU__memberData__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} memberData;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetDataSetDirectory_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetDataSetDirectory_ResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetDataSetDirectory_ResponsePDU_H_ */
#include <asn_internal.h>
