/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_GetLogicalNodeDirectory_RequestPDU_H_
#define	_GetLogicalNodeDirectory_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ACSIClass.h"
#include "ObjectReference.h"
#include "ObjectName.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetLogicalNodeDirectory_RequestPDU__reference_PR {
	GetLogicalNodeDirectory_RequestPDU__reference_PR_NOTHING,	/* No components present */
	GetLogicalNodeDirectory_RequestPDU__reference_PR_ldName,
	GetLogicalNodeDirectory_RequestPDU__reference_PR_lnReference
} GetLogicalNodeDirectory_RequestPDU__reference_PR;

/* GetLogicalNodeDirectory-RequestPDU */
typedef struct GetLogicalNodeDirectory_RequestPDU {
	struct GetLogicalNodeDirectory_RequestPDU__reference {
		GetLogicalNodeDirectory_RequestPDU__reference_PR present;
		union GetLogicalNodeDirectory_RequestPDU__reference_u {
			ObjectName_t	 ldName;
			ObjectReference_t	 lnReference;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} reference;
	ACSIClass_t	 acsiClass;
	ObjectReference_t	*referenceAfter;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetLogicalNodeDirectory_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetLogicalNodeDirectory_RequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetLogicalNodeDirectory_RequestPDU_H_ */
#include <asn_internal.h>
