/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_GetLogicalDeviceDirectory_RequestPDU_H_
#define	_GetLogicalDeviceDirectory_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "ObjectReference.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetLogicalDeviceDirectory-RequestPDU */
typedef struct GetLogicalDeviceDirectory_RequestPDU {
	ObjectName_t	*ldName;	/* OPTIONAL */
	ObjectReference_t	*referenceAfter;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetLogicalDeviceDirectory_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetLogicalDeviceDirectory_RequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetLogicalDeviceDirectory_RequestPDU_H_ */
#include <asn_internal.h>
