/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_GetSGCBValues_ResponsePDU_H_
#define	_GetSGCBValues_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "ServiceError.h"
#include "SGCB.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetSGCBValues_ResponsePDU__sgcb__Member_PR {
	GetSGCBValues_ResponsePDU__sgcb__Member_PR_NOTHING,	/* No components present */
	GetSGCBValues_ResponsePDU__sgcb__Member_PR_error,
	GetSGCBValues_ResponsePDU__sgcb__Member_PR_value
} GetSGCBValues_ResponsePDU__sgcb__Member_PR;

/* Forward definitions */
typedef struct GetSGCBValues_ResponsePDU__sgcb__Member {
	GetSGCBValues_ResponsePDU__sgcb__Member_PR present;
	union GetSGCBValues_ResponsePDU__sgcb__Member_u {
		ServiceError_t	 error;
		SGCB_t	 value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetSGCBValues_ResponsePDU__sgcb__Member;

/* GetSGCBValues-ResponsePDU */
typedef struct GetSGCBValues_ResponsePDU {
	struct GetSGCBValues_ResponsePDU__sgcb {
		A_SEQUENCE_OF(GetSGCBValues_ResponsePDU__sgcb__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sgcb;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetSGCBValues_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetSGCBValues_ResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetSGCBValues_ResponsePDU_H_ */
#include <asn_internal.h>
