/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_GetURCBValues_ResponsePDU_H_
#define	_GetURCBValues_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "ServiceError.h"
#include "URCB.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetURCBValues_ResponsePDU__urcb__Member_PR {
	GetURCBValues_ResponsePDU__urcb__Member_PR_NOTHING,	/* No components present */
	GetURCBValues_ResponsePDU__urcb__Member_PR_error,
	GetURCBValues_ResponsePDU__urcb__Member_PR_value
} GetURCBValues_ResponsePDU__urcb__Member_PR;

/* Forward definitions */
typedef struct GetURCBValues_ResponsePDU__urcb__Member {
	GetURCBValues_ResponsePDU__urcb__Member_PR present;
	union GetURCBValues_ResponsePDU__urcb__Member_u {
		ServiceError_t	 error;
		URCB_t	 value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetURCBValues_ResponsePDU__urcb__Member;

/* GetURCBValues-ResponsePDU */
typedef struct GetURCBValues_ResponsePDU {
	struct GetURCBValues_ResponsePDU__urcb {
		A_SEQUENCE_OF(GetURCBValues_ResponsePDU__urcb__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} urcb;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetURCBValues_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetURCBValues_ResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetURCBValues_ResponsePDU_H_ */
#include <asn_internal.h>
