/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_INT32_H_
#define	_INT32_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* INT32 */
typedef long	 INT32_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_INT32_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_INT32;
asn_struct_free_f INT32_free;
asn_struct_print_f INT32_print;
asn_constr_check_f INT32_constraint;
per_type_decoder_f INT32_decode_uper;
per_type_encoder_f INT32_encode_uper;
per_type_decoder_f INT32_decode_aper;
per_type_encoder_f INT32_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _INT32_H_ */
#include <asn_internal.h>
