/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_INT32U_H_
#define	_INT32U_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* INT32U */
typedef unsigned long	 INT32U_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_INT32U_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_INT32U;
extern const asn_INTEGER_specifics_t asn_SPC_INT32U_specs_1;
asn_struct_free_f INT32U_free;
asn_struct_print_f INT32U_print;
asn_constr_check_f INT32U_constraint;
per_type_decoder_f INT32U_decode_uper;
per_type_encoder_f INT32U_encode_uper;
per_type_decoder_f INT32U_decode_aper;
per_type_encoder_f INT32U_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _INT32U_H_ */
#include <asn_internal.h>
