/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_MSVCB_H_
#define	_MSVCB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "VisibleString129.h"
#include "ObjectReference.h"
#include "INT32U.h"
#include "SmpMod.h"
#include "INT16U.h"
#include "MSVCBOptFlds.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PHYCOMADDR;

/* MSVCB */
typedef struct MSVCB {
	BOOLEAN_t	 svEna;
	VisibleString129_t	 msvID;
	ObjectReference_t	 datSet;
	INT32U_t	 confRev;
	SmpMod_t	*smpMod;	/* OPTIONAL */
	INT16U_t	 smpRate;
	MSVCBOptFlds_t	 optFlds;
	struct PHYCOMADDR	*dstAddress;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MSVCB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MSVCB;
extern asn_SEQUENCE_specifics_t asn_SPC_MSVCB_specs_1;
extern asn_TYPE_member_t asn_MBR_MSVCB_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PHYCOMADDR.h"

#endif	/* _MSVCB_H_ */
#include <asn_internal.h>
