/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_ObjectName_H_
#define	_ObjectName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ObjectName */
typedef VisibleString_t	 ObjectName_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ObjectName_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ObjectName;
asn_struct_free_f ObjectName_free;
asn_struct_print_f ObjectName_print;
asn_constr_check_f ObjectName_constraint;
per_type_decoder_f ObjectName_decode_uper;
per_type_encoder_f ObjectName_encode_uper;
per_type_decoder_f ObjectName_decode_aper;
per_type_encoder_f ObjectName_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectName_H_ */
#include <asn_internal.h>
