/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_Octet64_H_
#define	_Octet64_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Octet64 */
typedef OCTET_STRING_t	 Octet64_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Octet64;
asn_struct_free_f Octet64_free;
asn_struct_print_f Octet64_print;
asn_constr_check_f Octet64_constraint;
per_type_decoder_f Octet64_decode_uper;
per_type_encoder_f Octet64_encode_uper;
per_type_decoder_f Octet64_decode_aper;
per_type_encoder_f Octet64_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Octet64_H_ */
#include <asn_internal.h>
