/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_PHYCOMADDR_H_
#define	_PHYCOMADDR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "INT8U.h"
#include "INT16U.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PHYCOMADDR */
typedef struct PHYCOMADDR {
	OCTET_STRING_t	 addr;
	INT8U_t	 priority;
	INT16U_t	 vid;
	INT16U_t	 appid;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PHYCOMADDR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PHYCOMADDR;
extern asn_SEQUENCE_specifics_t asn_SPC_PHYCOMADDR_specs_1;
extern asn_TYPE_member_t asn_MBR_PHYCOMADDR_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _PHYCOMADDR_H_ */
#include <asn_internal.h>
