/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_ReasonCode_H_
#define	_ReasonCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReasonCode {
	ReasonCode_reserved	= 0,
	ReasonCode_data_change	= 1,
	ReasonCode_quality_change	= 2,
	ReasonCode_data_update	= 3,
	ReasonCode_integrity	= 4,
	ReasonCode_general_interrogation	= 5,
	ReasonCode_application_trigger	= 6
} e_ReasonCode;

/* ReasonCode */
typedef BIT_STRING_t	 ReasonCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReasonCode;
asn_struct_free_f ReasonCode_free;
asn_struct_print_f ReasonCode_print;
asn_constr_check_f ReasonCode_constraint;
per_type_decoder_f ReasonCode_decode_uper;
per_type_encoder_f ReasonCode_encode_uper;
per_type_decoder_f ReasonCode_decode_aper;
per_type_encoder_f ReasonCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReasonCode_H_ */
#include <asn_internal.h>
