/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_SetBRCBValues_RequestPDU_H_
#define	_SetBRCBValues_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "ObjectReference.h"
#include "VisibleString129.h"
#include <BOOLEAN.h>
#include "RCBOptFlds.h"
#include "INT32U.h"
#include "TriggerConditions.h"
#include "EntryID.h"
#include "INT16.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct SetBRCBValues_RequestPDU__brcb__Member {
	ObjectReference_t	 reference;
	VisibleString129_t	*rptID;	/* OPTIONAL */
	BOOLEAN_t	*rptEna;	/* OPTIONAL */
	ObjectReference_t	*datSet;	/* OPTIONAL */
	RCBOptFlds_t	*optFlds;	/* OPTIONAL */
	INT32U_t	*bufTm;	/* OPTIONAL */
	TriggerConditions_t	*trgOps;	/* OPTIONAL */
	INT32U_t	*intgPd;	/* OPTIONAL */
	BOOLEAN_t	*gi;	/* OPTIONAL */
	BOOLEAN_t	*purgeBuf;	/* OPTIONAL */
	EntryID_t	*entryID;	/* OPTIONAL */
	INT16_t	*resvTms;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetBRCBValues_RequestPDU__brcb__Member;

/* SetBRCBValues-RequestPDU */
typedef struct SetBRCBValues_RequestPDU {
	struct SetBRCBValues_RequestPDU__brcb {
		A_SEQUENCE_OF(SetBRCBValues_RequestPDU__brcb__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} brcb;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetBRCBValues_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetBRCBValues_RequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _SetBRCBValues_RequestPDU_H_ */
#include <asn_internal.h>
