/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_SetDataValues_ResponsePDU_H_
#define	_SetDataValues_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetDataValues-ResponsePDU */
typedef NULL_t	 SetDataValues_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetDataValues_ResponsePDU;
asn_struct_free_f SetDataValues_ResponsePDU_free;
asn_struct_print_f SetDataValues_ResponsePDU_print;
asn_constr_check_f SetDataValues_ResponsePDU_constraint;
per_type_decoder_f SetDataValues_ResponsePDU_decode_uper;
per_type_encoder_f SetDataValues_ResponsePDU_encode_uper;
per_type_decoder_f SetDataValues_ResponsePDU_decode_aper;
per_type_encoder_f SetDataValues_ResponsePDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SetDataValues_ResponsePDU_H_ */
#include <asn_internal.h>
