/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_SetURCBValues_ErrorPDU_H_
#define	_SetURCBValues_ErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "ServiceError.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct SetURCBValues_ErrorPDU__result__Member {
	ServiceError_t	*error;	/* OPTIONAL */
	ServiceError_t	*rptID;	/* OPTIONAL */
	ServiceError_t	*rptEna;	/* OPTIONAL */
	ServiceError_t	*datSet;	/* OPTIONAL */
	ServiceError_t	*optFlds;	/* OPTIONAL */
	ServiceError_t	*bufTm;	/* OPTIONAL */
	ServiceError_t	*trgOps;	/* OPTIONAL */
	ServiceError_t	*intgPd;	/* OPTIONAL */
	ServiceError_t	*gi;	/* OPTIONAL */
	ServiceError_t	*resv;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetURCBValues_ErrorPDU__result__Member;

/* SetURCBValues-ErrorPDU */
typedef struct SetURCBValues_ErrorPDU {
	struct SetURCBValues_ErrorPDU__result {
		A_SEQUENCE_OF(SetURCBValues_ErrorPDU__result__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} result;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetURCBValues_ErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetURCBValues_ErrorPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _SetURCBValues_ErrorPDU_H_ */
#include <asn_internal.h>
