/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_SGCB_H_
#define	_SGCB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "INT8U.h"
#include "TimeStamp.h"
#include "INT16U.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SGCB */
typedef struct SGCB {
	INT8U_t	 numOfSG;
	INT8U_t	 actSG;
	INT8U_t	 editSG;
	TimeStamp_t	 lActTm;
	INT16U_t	*resvTms;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SGCB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGCB;
extern asn_SEQUENCE_specifics_t asn_SPC_SGCB_specs_1;
extern asn_TYPE_member_t asn_MBR_SGCB_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _SGCB_H_ */
#include <asn_internal.h>
