/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_Tcmd_H_
#define	_Tcmd_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Tcmd */
typedef BIT_STRING_t	 Tcmd_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Tcmd_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Tcmd;
asn_struct_free_f Tcmd_free;
asn_struct_print_f Tcmd_print;
asn_constr_check_f Tcmd_constraint;
per_type_decoder_f Tcmd_decode_uper;
per_type_encoder_f Tcmd_encode_uper;
per_type_decoder_f Tcmd_decode_aper;
per_type_encoder_f Tcmd_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Tcmd_H_ */
#include <asn_internal.h>
