/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_TimeStamp_H_
#define	_TimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UtcTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TimeStamp */
typedef UtcTime_t	 TimeStamp_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimeStamp_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimeStamp;
asn_struct_free_f TimeStamp_free;
asn_struct_print_f TimeStamp_print;
asn_constr_check_f TimeStamp_constraint;
per_type_decoder_f TimeStamp_decode_uper;
per_type_encoder_f TimeStamp_encode_uper;
per_type_decoder_f TimeStamp_decode_aper;
per_type_encoder_f TimeStamp_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeStamp_H_ */
#include <asn_internal.h>
