/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_UnicodeString255_H_
#define	_UnicodeString255_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UnicodeString255 */
typedef VisibleString_t	 UnicodeString255_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnicodeString255;
asn_struct_free_f UnicodeString255_free;
asn_struct_print_f UnicodeString255_print;
asn_constr_check_f UnicodeString255_constraint;
per_type_decoder_f UnicodeString255_decode_uper;
per_type_encoder_f UnicodeString255_encode_uper;
per_type_decoder_f UnicodeString255_decode_aper;
per_type_encoder_f UnicodeString255_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UnicodeString255_H_ */
#include <asn_internal.h>
