/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CMS61850Module"
 * 	found in "./61850CMS.asn"
 * 	`asn1c -D ./out -gen-APER -no-gen-BER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-example -fcompound-names`
 */

#ifndef	_UtcTime_H_
#define	_UtcTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UtcTime */
typedef OCTET_STRING_t	 UtcTime_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UtcTime_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UtcTime;
asn_struct_free_f UtcTime_free;
asn_struct_print_f UtcTime_print;
asn_constr_check_f UtcTime_constraint;
per_type_decoder_f UtcTime_decode_uper;
per_type_encoder_f UtcTime_encode_uper;
per_type_decoder_f UtcTime_decode_aper;
per_type_encoder_f UtcTime_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UtcTime_H_ */
#include <asn_internal.h>
